DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS voucher;
DROP TABLE IF EXISTS acmeTransaction;
DROP TABLE IF EXISTS product;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  nickname TEXT NOT NULL,
  password TEXT NOT NULL,
  paymentCard INTEGER NOT NULL,
  userPublicKey TEXT NOT NULL
);

CREATE TABLE voucher (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ownerID INTEGER NOT NULL,
  discount INTEGER NOT NULL,
  FOREIGN KEY (ownerID) REFERENCES user (id)
);

CREATE TABLE acmeTransaction (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ownerID INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  total INTEGER NOT NULL,
  discounted INTEGER NOT NULL,
  voucherID INTEGER DEFAULT NULL,
  FOREIGN KEY (ownerID) REFERENCES user (id)
  FOREIGN KEY (voucherID) REFERENCES voucher (id)
);

CREATE TABLE product (
  code INTEGER PRIMARY KEY AUTOINCREMENT,
  price INTEGER NOT NULL,
  prodName TEXT NOT NULL
);

CREATE TABLE transactionProdcuts (
  transactionID INTEGER NOT NULL,
  productID INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,
  FOREIGN KEY (transactionID) REFERENCES acmeTransaction (id)
  FOREIGN KEY (productID) REFERENCES product (id)
  PRIMARY KEY (transactionID, productID)
);
